#!/usr/bin/env ruby
`chmod +x rmanedit`
`cp rmanedit /usr/bin/rmanedit`
`cp -r images /usr/share/pixmaps`
if not File::directory?("~/.config/rmanedit")
`mkdir ~/.config/rmanedit`
end
`cp lang.rb ~/.config/rmanedit`
`chown #{ENV['USER']} ~/.config/rmanedit/lang.rb`
puts ENV['USER']
if not File::directory?( "/usr/local/share/locale/tr/LC_MESSAGES" ) 
  `mkdir -p /usr/local/share/locale/tr/LC_MESSAGES`
end
`rmsgfmt po/tr/rmanedit.po -o /usr/local/share/locale/tr/LC_MESSAGES/rmanedit.mo`
