#!/usr/bin/env ruby

begin 
  arr = Array.new
  Dir.foreach(Dir.pwd){|file|; arr.push(file);}
  # ilk kurulum
  if arr.index("images") != nil
    if not File::directory?("~/.config/rmanedit")
      `mkdir ~/.config/rmanedit`
    end
    `mv lang.rb ~/.config/rmanedit`
    `sudo chmod +x bin/rmanedit`
    `sudo cp bin/rmanedit /usr/bin/rmanedit`
    `sudo mv images /usr/share/pixmaps`
    if not File::directory?( "/usr/local/share/locale/tr/LC_MESSAGES" ) 
      `sudo mkdir -p /usr/local/share/locale/tr/LC_MESSAGES`
    end
    `sudo rmsgfmt po/tr/rmanedit.po -o /usr/local/share/locale/tr/LC_MESSAGES/rmanedit.mo`
  end
rescue
  puts "installation error"
end
