#!/usr/bin/env ruby
if not File::directory?("~/.config/rmanedit")
`sudo mkdir ~/.config/rmanedit`
end
`sudo cp /lang.rb ~/.config/rmanedit`
`sudo chmod +x rmanedit`
`sudo cp /rmanedit /usr/bin/rmanedit`
`sudo cp -r /images /usr/share/pixmaps`
`sudo mkdir -p /var/lib/gems/1.9.1/gems/RManEdit-1.0.0/lib/`
`sudo cp /lib/utils.rb /var/lib/gems/1.9.1/gems/RManEdit-1.0.0/lib/utils.rb`
if not File::directory?( "/usr/local/share/locale/tr/LC_MESSAGES" )
  `sudo mkdir -p /usr/local/share/locale/tr/LC_MESSAGES`
end
`sudo rmsgfmt /po/tr/rmanedit.po -o /usr/local/share/locale/tr/LC_MESSAGES/rmanedit.mo`
